//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable_2_WireFrames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityLeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CommunityLeader()
        {
            this.LeaderTypes = new HashSet<LeaderType>();
            this.Collections = new HashSet<Collection>();
        }
    
        public int CommunityLeader_ID { get; set; }
        public string CommunityLeader_Name { get; set; }
        public string CommunityLeader_Surname { get; set; }
        public decimal CommunityLeader_PhoneNumber { get; set; }
        public string CommunityLeader_Race { get; set; }
        public Nullable<int> Village_ID { get; set; }
    
        public virtual Village Village { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LeaderType> LeaderTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collection> Collections { get; set; }
    }
}
