//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable_2_WireFrames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.MedicalPractitioners = new HashSet<MedicalPractitioner>();
        }
    
        public int Doctor_ID { get; set; }
        public string Doctor_Name { get; set; }
        public string Doctor_Surname { get; set; }
        public string Doctor_Email { get; set; }
        public decimal Doctor_PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalPractitioner> MedicalPractitioners { get; set; }
    }
}
