//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable_2_WireFrames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Consultations = new HashSet<Consultation>();
            this.MedicalRecords = new HashSet<MedicalRecord>();
        }
    
        public int Patient_ID { get; set; }
        public string Patient_Name { get; set; }
        public string Patient_Surname { get; set; }
        public decimal Patient_PhoneNumber { get; set; }
        public string Patient_IDNumber { get; set; }
        public string Patient_Race { get; set; }
        public Nullable<int> Gender_ID { get; set; }
        public Nullable<int> City_ID { get; set; }
        public Nullable<int> Village_ID { get; set; }
    
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consultation> Consultations { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalRecord> MedicalRecords { get; set; }
        public virtual Village Village { get; set; }
    }
}
