//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable_2_WireFrames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrescriptionLine
    {
        public int PrescriptionLine_ID { get; set; }
        public string PrescriptionLine_Quantity { get; set; }
        public int Prescription_ID { get; set; }
        public Nullable<int> Medication_ID { get; set; }
    
        public virtual Medication Medication { get; set; }
        public virtual Prescription Prescription { get; set; }
    }
}
