//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deliverable_2_WireFrames.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public int Region_ID { get; set; }
        public string Region_Name { get; set; }
    }
}
